title: Switch2OSM
description: >
  Переходьте на OpenStreetMap та дізнайтесь як ви можете робити чудові мапи
  з найповніших даних, зібраних по всьому світу.
baseurl: "/switch2osm" # the subpath of your site, e.g. /blog
copyright: 2013–2020 OpenStreetMap та його учасникі, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA</a>
url: ""
background: assets/img/body-bg-uk.png
github_username: osm-ua
google_analytics: UA-64679388-3

# Build settings
markdown: kramdown

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

menu:
  - title: Навіщо?
    url: /why-switch/
  - title: Вже з OSM
    url: /case-studies/
  - title: Основи
    url: /the-basics/
  - title: Мапа
    url: /using-tiles/
  - title: Власний сервер
    url: /serving-tiles/
  - title: Інше
    url: /other-uses/
  - title: Постачальники
    url: /providers/
  - title: Дізнатися більше
    url: /find-out-more/
